spring.application.name=InternProject

spring.datasource.url=jdbc:postgresql://localhost:5432/UserDatabase
spring.datasource.username=postgres
spring.datasource.password=Bhargavi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=S6P6QCfKOeHBOC7nTiSO4MYsTUNURABWFLL8OCyFIos=


logging.level.org.springframework.security=DEBUG